/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfac;

import connection.ConsultaCNPJController;
import connection.PessoaJuridica;
import Jm.JMascara;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.JOptionPane;
import model.transportadora;
import modelDAO.ExcluirDAO;
import modelDAO.IncluirEditarDAO;
import modelDAO.PesquisaDAO;
import java.sql.SQLException;
import java.util.Iterator;
import org.dom4j.Document;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;

/**
 * Usuario pode CONSULTAR, Cadastrar, Alterar e Excluir TRANSPORTADORA
 *
 */
public class jifTransportadora extends javax.swing.JInternalFrame {

    int acao;
    int status;

    private ConsultaCNPJController controller;

    transportadora objtra = new transportadora();

    IncluirEditarDAO IEDAO;
    ExcluirDAO EXDAO;
    PesquisaDAO PESDAO;

    /**
     * Creates new form Transportadora
     */
    public jifTransportadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAtividade = new javax.swing.ButtonGroup();
        jSeparator5 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jlRazaoS = new javax.swing.JLabel();
        jtRazaoS = new javax.swing.JTextField();
        jlApelido = new javax.swing.JLabel();
        jtApelido = new javax.swing.JTextField();
        jbBuscarT = new javax.swing.JButton();
        jlCod = new javax.swing.JLabel();
        jtCod = new javax.swing.JTextField();
        jliE = new javax.swing.JLabel();
        jtiE = new javax.swing.JTextField();
        jlCnpj = new javax.swing.JLabel();
        jrAtivo = new javax.swing.JRadioButton();
        jrInativo = new javax.swing.JRadioButton();
        jtPlat = new javax.swing.JLabel();
        jcPlat = new javax.swing.JComboBox<>();
        jlEmpi = new javax.swing.JLabel();
        jcEmpi = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jtCnpj = new javax.swing.JFormattedTextField();
        jcPessoa = new javax.swing.JComboBox<>();
        jlPessoa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlInfoCon = new javax.swing.JLabel();
        jlTelCel = new javax.swing.JLabel();
        jtTelCel = new javax.swing.JFormattedTextField();
        jlTelFixo = new javax.swing.JLabel();
        jtTelFixo = new javax.swing.JFormattedTextField();
        jlEmpresa = new javax.swing.JLabel();
        jlEmailCon = new javax.swing.JLabel();
        jtMailCon = new javax.swing.JTextField();
        jlEndWeb = new javax.swing.JLabel();
        jtEndWeb = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jlVeiculo = new javax.swing.JLabel();
        jlveiCon = new javax.swing.JLabel();
        jtNomeCon = new javax.swing.JTextField();
        jtRntrc = new javax.swing.JTextField();
        jlrntrc = new javax.swing.JLabel();
        jtChapaV = new javax.swing.JTextField();
        jtTelCon = new javax.swing.JTextField();
        jlveiChapa = new javax.swing.JLabel();
        jlveiTel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jtQuem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbCnpj = new javax.swing.JButton();
        jtAcesso = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jlEnd = new javax.swing.JLabel();
        jlCep = new javax.swing.JLabel();
        jtCep = new javax.swing.JFormattedTextField();
        jbCep = new javax.swing.JButton();
        jtBairro = new javax.swing.JTextField();
        jlBairro = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jlRua = new javax.swing.JLabel();
        jtNum = new javax.swing.JTextField();
        jlNum = new javax.swing.JLabel();
        jtCompl = new javax.swing.JTextField();
        jlCompl = new javax.swing.JLabel();
        jtCidade = new javax.swing.JTextField();
        jlCidade = new javax.swing.JLabel();
        jcUf = new javax.swing.JComboBox<>();
        jlEstado = new javax.swing.JLabel();
        jlCodIbge = new javax.swing.JLabel();
        jtCodIbge = new javax.swing.JTextField();
        jtHoraAtend = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtContato = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Transportadora");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jlRazaoS.setText("Razão Social");

        jtRazaoS.setEnabled(false);

        jlApelido.setText("Apelido");

        jtApelido.setEnabled(false);

        jbBuscarT.setText("...");
        jbBuscarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarTActionPerformed(evt);
            }
        });

        jlCod.setText("Cod.");

        jtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCodKeyPressed(evt);
            }
        });

        jliE.setText("Inscrição Estadual");

        jtiE.setEnabled(false);
        jtiE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtiEKeyTyped(evt);
            }
        });

        jlCnpj.setText("CNPJ");

        jbAtividade.add(jrAtivo);
        jrAtivo.setText("Ativo");
        jrAtivo.setEnabled(false);

        jbAtividade.add(jrInativo);
        jrInativo.setText("Inativo");
        jrInativo.setEnabled(false);

        jtPlat.setText("Plataforma");

        jcPlat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SIM", "NÃO" }));
        jcPlat.setEnabled(false);

        jlEmpi.setText("Empilhadeira");

        jcEmpi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SIM", "NÃO" }));
        jcEmpi.setEnabled(false);

        jtCnpj.setEnabled(false);
        jtCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCnpjKeyReleased(evt);
            }
        });

        jcPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "FÍSICA", "JURÍDICA" }));
        jcPessoa.setEnabled(false);

        jlPessoa.setText("Pessoa");

        jlInfoCon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlInfoCon.setText("Informações de Contato: ");

        jlTelCel.setText("Telefone Celular");

        jtTelCel.setEnabled(false);
        jtTelCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTelCelKeyReleased(evt);
            }
        });

        jlTelFixo.setText("Telefone Fixo");

        jtTelFixo.setEnabled(false);
        jtTelFixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTelFixoKeyReleased(evt);
            }
        });

        jlEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlEmpresa.setText("Empresa");

        jlEmailCon.setText("E-mail Contato");

        jtMailCon.setEnabled(false);

        jlEndWeb.setText("End. Web");

        jtEndWeb.setEnabled(false);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlVeiculo.setText("Veículo");

        jlveiCon.setText("Nome (Contato)");

        jtNomeCon.setEnabled(false);

        jtRntrc.setEnabled(false);

        jlrntrc.setText("RNTRC");

        jtChapaV.setEnabled(false);

        jtTelCon.setEnabled(false);
        jtTelCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTelConKeyReleased(evt);
            }
        });

        jlveiChapa.setText("Chapa Veículo");

        jlveiTel.setText("Telefone de Contato");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jtQuem.setEnabled(false);
        jtQuem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtQuemActionPerformed(evt);
            }
        });

        jLabel8.setText("Usuário Responsável");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlEmailCon, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtEndWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlInfoCon)
                            .addComponent(jlEmpresa)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtTelCel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jlEndWeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jtMailCon, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlVeiculo)
                            .addComponent(jtNomeCon)
                            .addComponent(jtRntrc)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlveiCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlrntrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jlveiChapa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtChapaV, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtTelCon, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlveiTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbSalvar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbExcluir))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbSair))
                            .addComponent(jtQuem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCancelar, jbEditar, jbExcluir, jbNovo, jbSair, jbSalvar});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtChapaV, jtNomeCon, jtRntrc, jtTelCon});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtEndWeb, jtMailCon});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlInfoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmpresa)
                    .addComponent(jlVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTelCel)
                            .addComponent(jlEmailCon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtMailCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTelFixo)
                            .addComponent(jlEndWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtEndWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlveiCon)
                            .addComponent(jlveiTel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNomeCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtTelCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlrntrc)
                            .addComponent(jlveiChapa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtRntrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtChapaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtQuem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jSeparator6)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtChapaV, jtEndWeb, jtMailCon, jtNomeCon, jtRntrc, jtTelCel, jtTelCon, jtTelFixo});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlEmailCon, jlEndWeb, jlTelCel, jlTelFixo, jlrntrc, jlveiChapa, jlveiCon, jlveiTel});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbCancelar, jbEditar, jbExcluir, jbNovo, jbSair, jbSalvar});

        jbCnpj.setText("...");
        jbCnpj.setEnabled(false);
        jbCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCnpjActionPerformed(evt);
            }
        });

        jtAcesso.setEnabled(false);

        jlEnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlEnd.setText("Endereço:");

        jlCep.setText("CEP");

        jtCep.setEnabled(false);
        jtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCepKeyReleased(evt);
            }
        });

        jbCep.setText("jButton1");
        jbCep.setEnabled(false);
        jbCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCepActionPerformed(evt);
            }
        });

        jtBairro.setEnabled(false);

        jlBairro.setText("Bairro");

        jtRua.setEnabled(false);

        jlRua.setText("Logradouro");

        jtNum.setEnabled(false);

        jlNum.setText("N°");

        jtCompl.setEnabled(false);

        jlCompl.setText("Complemento*");

        jtCidade.setEnabled(false);

        jlCidade.setText("Cidade");

        jcUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jcUf.setEnabled(false);

        jlEstado.setText("UF");

        jlCodIbge.setText("Cod. IBGE");

        jtCodIbge.setEnabled(false);
        jtCodIbge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCodIbgeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEnd)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCep, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRua, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcUf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlBairro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtCodIbge, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCodIbge, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jlEnd)
                            .addGap(28, 28, 28))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNum)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlRua)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jlCidade)
                        .addGap(5, 5, 5)
                        .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlCodIbge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCodIbge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlCep)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbCep, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlBairro)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlCompl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbCep, jcUf, jtBairro, jtCep, jtCidade, jtCodIbge, jtCompl, jtNum, jtRua});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlBairro, jlCep, jlCidade, jlCompl, jlEnd, jlEstado, jlNum, jlRua});

        jtHoraAtend.setEnabled(false);

        jLabel15.setText("Horário de Atendimento");

        jtContato.setEnabled(false);

        jLabel16.setText("Contato");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtiE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jliE, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcPlat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcEmpi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlEmpi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtHoraAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtContato)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlCod, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbBuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtRazaoS, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlRazaoS, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrInativo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcEmpi, jcPessoa, jcPlat});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbBuscarT, jbCnpj});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtContato, jtiE});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlRazaoS)
                                .addComponent(jlCnpj))
                            .addComponent(jlCod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtRazaoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCnpj)
                            .addComponent(jrAtivo)
                            .addComponent(jrInativo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jtAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlApelido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtPlat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jliE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtiE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlEmpi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcEmpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtHoraAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcEmpi, jcPessoa, jcPlat, jtApelido, jtCnpj, jtCod, jtContato, jtRazaoS, jtiE});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlApelido, jlCnpj, jlCod, jlEmpi, jlPessoa, jlRazaoS, jliE, jtPlat});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbBuscarT, jbCnpj});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(250, 20, 921, 514);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:

        jPrincipal.transportadora = true;

        jrAtivo.setSelected(true);
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:

        jPrincipal.transportadora = false;
        dispose();
    }//GEN-LAST:event_formInternalFrameClosed

    private void jtCodIbgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCodIbgeKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtCodIbgeKeyTyped

    private void jbCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCepActionPerformed
        buscarCep(JMascara.GetJmascaraLimpar(jtCep.getText()));
    }//GEN-LAST:event_jbCepActionPerformed

    private void jtCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCepKeyReleased
        // TODO add your handling code here:

        jtCep.setText(JMascara.GetJmascaraCep(jtCep.getText()));

        if (jtCep.getText().length() == 8) {
            buscarCep(jtCep.getText());
        }
    }//GEN-LAST:event_jtCepKeyReleased

    private void jbCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCnpjActionPerformed
        // TODO add your handling code here:

        buscarCNPJ();
    }//GEN-LAST:event_jbCnpjActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        jPrincipal.transportadora = false;
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed

        cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        if (jtCod.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o Código! ");
        } else {
            int codigo = Integer.parseInt(jtCod.getText());

            EXDAO = new ExcluirDAO();

            try {
                if (JOptionPane.showConfirmDialog(this, "Confirmar Exclusão? ", "Confirmação",
                    JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_NO_OPTION) {
                if (EXDAO.ExcluirTransportadora(codigo)) {
                    JOptionPane.showMessageDialog(this, "Excluido com sucesso!");
                    cancelar();

                } else {

                    JOptionPane.showMessageDialog(this, "Erro ao excluir o registro! ");

                }
            } else {

                JOptionPane.showMessageDialog(this, "Operação cancelada! ");
                cancelar();

            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(this, "Erro: Exclusão Não REalizada!" + error.getMessage());
        }

        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed

        acao = 2;
        editar();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        if (jrAtivo.isSelected()) {
            status = 1;
        }
        if (jrInativo.isSelected()) {
            status = 0;
        }

        int Cod;
        objtra = new transportadora();
        preencher_objetos();

        try {

            IEDAO = new IncluirEditarDAO();

            if (acao == 1) {

                jtQuem.setText("Cadastro Realizado por " + jtAcesso.getText());
                preencher_objetos();
                salvar();

                Cod = IEDAO.IncluirTransportadora(objtra);
                jtCod.setText(String.valueOf(Cod));
                JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + error.getMessage());
            cancelar();

        }
        if (acao == 2) {
            salvar();

            objtra.setId_transportadora(Integer.parseInt(jtCod.getText()));

            try {
                if (IEDAO.EditarTransportadora(objtra)) {

                    JOptionPane.showMessageDialog(this, "Alterado com Sucesso!");

                }
            } catch (SQLException ex) {
                System.err.println("Erro: " + ex);
            }

        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed

        acao = 1;

        novo();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jtTelConKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelConKeyReleased
        // TODO add your handling code here:

        jtTelCon.setText(JMascara.GetJmascaraFone(jtTelCon.getText()));
    }//GEN-LAST:event_jtTelConKeyReleased

    private void jtTelFixoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelFixoKeyReleased
        // TODO add your handling code here:
        jtTelFixo.setText(JMascara.GetJmascaraFone(jtTelFixo.getText()));
    }//GEN-LAST:event_jtTelFixoKeyReleased

    private void jtTelCelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelCelKeyReleased
        // TODO add your handling code here:

        jtTelCel.setText(JMascara.GetJmascaraFone(jtTelCel.getText()));
    }//GEN-LAST:event_jtTelCelKeyReleased

    private void jtCnpjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCnpjKeyReleased
        // TODO add your handling code here:
        jtCnpj.setText(JMascara.GetJmascaraCpfCnpj(jtCnpj.getText()));
    }//GEN-LAST:event_jtCnpjKeyReleased

    private void jtiEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtiEKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtiEKeyTyped

    private void jtCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCodKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            objtra = new transportadora();
            if (jtCod.getText().isEmpty()) {

                jifConsultaTransp objconsulta = new jifConsultaTransp();
                jPrincipal.jTela.add(objconsulta);
                objconsulta.setVisible(true);
                jPrincipal.jTela.setComponentZOrder(objconsulta, 0);

            } else {
                objtra.setId_transportadora(Integer.parseInt(jtCod.getText()));

                PESDAO = new PesquisaDAO();

                try {

                    if (PESDAO.PesquisarTelaTransportadora(objtra)) {
                        if ((objtra != null)) {
                            pesquisaTransportadora();

                        }
                    }
                } catch (SQLException erro) {
                    JOptionPane.showMessageDialog(this, "Erro ao pesquisar " + erro.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jtCodKeyPressed

    private void jbBuscarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarTActionPerformed
        objtra = new transportadora();
        if (jtCod.getText().isEmpty()) {

            jifConsultaTransp objconsulta = new jifConsultaTransp();
            jPrincipal.jTela.add(objconsulta);
            objconsulta.setVisible(true);
            jPrincipal.jTela.setComponentZOrder(objconsulta, 0);

        } else {
            objtra.setId_transportadora(Integer.parseInt(jtCod.getText()));

            PESDAO = new PesquisaDAO();

            try {

                if (PESDAO.PesquisarTelaTransportadora(objtra)) {
                    if ((objtra != null)) {
                        pesquisaTransportadora();

                    }
                }
            } catch (SQLException erro) {
                JOptionPane.showMessageDialog(this, "Erro ao pesquisar " + erro.getMessage());
            }
        }
    }//GEN-LAST:event_jbBuscarTActionPerformed

    private void jtQuemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtQuemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtQuemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.ButtonGroup jbAtividade;
    private javax.swing.JButton jbBuscarT;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCep;
    private javax.swing.JButton jbCnpj;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcEmpi;
    private javax.swing.JComboBox<String> jcPessoa;
    private javax.swing.JComboBox<String> jcPlat;
    private javax.swing.JComboBox<String> jcUf;
    private javax.swing.JLabel jlApelido;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCep;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlCnpj;
    private javax.swing.JLabel jlCod;
    private javax.swing.JLabel jlCodIbge;
    private javax.swing.JLabel jlCompl;
    private javax.swing.JLabel jlEmailCon;
    private javax.swing.JLabel jlEmpi;
    private javax.swing.JLabel jlEmpresa;
    private javax.swing.JLabel jlEnd;
    private javax.swing.JLabel jlEndWeb;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlInfoCon;
    private javax.swing.JLabel jlNum;
    private javax.swing.JLabel jlPessoa;
    private javax.swing.JLabel jlRazaoS;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlTelCel;
    private javax.swing.JLabel jlTelFixo;
    private javax.swing.JLabel jlVeiculo;
    private javax.swing.JLabel jliE;
    private javax.swing.JLabel jlrntrc;
    private javax.swing.JLabel jlveiChapa;
    private javax.swing.JLabel jlveiCon;
    private javax.swing.JLabel jlveiTel;
    private javax.swing.JRadioButton jrAtivo;
    private javax.swing.JRadioButton jrInativo;
    private static javax.swing.JTextField jtAcesso;
    private javax.swing.JTextField jtApelido;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JFormattedTextField jtCep;
    private javax.swing.JTextField jtChapaV;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JFormattedTextField jtCnpj;
    private static javax.swing.JTextField jtCod;
    private javax.swing.JTextField jtCodIbge;
    private javax.swing.JTextField jtCompl;
    private javax.swing.JTextField jtContato;
    private javax.swing.JTextField jtEndWeb;
    private javax.swing.JTextField jtHoraAtend;
    private javax.swing.JTextField jtMailCon;
    private javax.swing.JTextField jtNomeCon;
    private javax.swing.JTextField jtNum;
    private javax.swing.JLabel jtPlat;
    private static javax.swing.JTextField jtQuem;
    private javax.swing.JTextField jtRazaoS;
    private javax.swing.JTextField jtRntrc;
    private javax.swing.JTextField jtRua;
    private javax.swing.JFormattedTextField jtTelCel;
    private javax.swing.JTextField jtTelCon;
    private javax.swing.JFormattedTextField jtTelFixo;
    private javax.swing.JTextField jtiE;
    // End of variables declaration//GEN-END:variables

    /**
     * RECEBE NOME DE USUARIO DE TELA PRINCIPAL
     *
     * @param objtra
     */
    public static void recebeUser(transportadora objtra) {
        jtQuem.setText(String.valueOf(objtra.getTra_quemCad()));
        jtAcesso.setText(jtQuem.getText());
    }

    /**
     * RECEBE CODIGO DO CLIENTE DE jifConsultaTransp
     *
     * @param objtra
     */
    public static void recebeidTransportadora(transportadora objtra) {
        jtCod.setText(String.valueOf(objtra.getId_transportadora()));
        jtCod.requestFocus();
    }

    /**
     * Funções do botão Salvar
     */
    public void salvar() {
        jbCnpj.setEnabled(true);

        jbExcluir.setEnabled(true);
        jbEditar.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbNovo.setEnabled(false);

        jtCod.setEnabled(true);
        jbBuscarT.setEnabled(true);

        jtCnpj.setEnabled(false);
        jtRazaoS.setEnabled(false);
        jtApelido.setEnabled(false);
        jtiE.setEnabled(false);
        jcPessoa.setEnabled(false);
        jcPlat.setEnabled(false);
        jcEmpi.setEnabled(false);

        jrAtivo.setEnabled(false);
        jrInativo.setEnabled(false);

        jtCep.setEnabled(false);
        jbCep.setEnabled(false);
        jtCodIbge.setEnabled(false);
        jtCidade.setEnabled(false);
        jcUf.setEnabled(false);
        jtBairro.setEnabled(false);
        jtCompl.setEnabled(false);
        jtNum.setEnabled(false);
        jtRua.setEnabled(false);

        jtTelFixo.setEnabled(false);
        jtTelCel.setEnabled(false);
        jtMailCon.setEnabled(false);
        jtEndWeb.setEnabled(false);
        jtNomeCon.setEnabled(false);
        jtRntrc.setEnabled(false);
        jtTelCon.setEnabled(false);
        jtChapaV.setEnabled(false);

        jtHoraAtend.setEnabled(false);
        jtContato.setEnabled(false);

    }

    /**
     * Função do botao Novo
     */
    public void novo() {

        jbCnpj.setEnabled(true);

        jtCnpj.setEnabled(true);
        jtRazaoS.setEnabled(true);
        jtApelido.setEnabled(true);
        jtiE.setEnabled(true);
        jcPessoa.setEnabled(true);
        jcPlat.setEnabled(true);
        jcEmpi.setEnabled(true);

        jrAtivo.setEnabled(true);
        jrInativo.setEnabled(true);

        jtCep.setEnabled(true);
        jbCep.setEnabled(true);
        jtCodIbge.setEnabled(true);
        jtCidade.setEnabled(true);
        jcUf.setEnabled(true);
        jtBairro.setEnabled(true);
        jtCompl.setEnabled(true);
        jtNum.setEnabled(true);
        jtRua.setEnabled(true);

        jtTelFixo.setEnabled(true);
        jtTelCel.setEnabled(true);
        jtMailCon.setEnabled(true);
        jtEndWeb.setEnabled(true);
        jtNomeCon.setEnabled(true);
        jtRntrc.setEnabled(true);
        jtTelCon.setEnabled(true);
        jtChapaV.setEnabled(true);

        jtHoraAtend.setEnabled(true);
        jtContato.setEnabled(true);

        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);

        jtCod.setEnabled(false);
        jbBuscarT.setEnabled(false);

        //
        jtCod.setText("");
        jtCnpj.setText("");
        jtRazaoS.setText("");
        jtApelido.setText("");
        jtiE.setText("");
        jcPessoa.setSelectedIndex(0);
        jcPlat.setSelectedIndex(0);
        jcEmpi.setSelectedIndex(0);

        jtCep.setText("");
        jtCodIbge.setText("");
        jtCidade.setText("");
        jcUf.setSelectedIndex(0);
        jtBairro.setText("");
        jtCompl.setText("");
        jtNum.setText("");
        jtRua.setText("");

        jtTelFixo.setText("");
        jtTelCel.setText("");
        jtMailCon.setText("");
        jtEndWeb.setText("");
        jtNomeCon.setText("");
        jtRntrc.setText("");
        jtTelCon.setText("");
        jtChapaV.setText("");

    }

    /**
     * Função do botao editar
     */
    public void editar() {

        jbCnpj.setEnabled(true);

        jtCnpj.setEnabled(true);
        jtRazaoS.setEnabled(true);
        jtApelido.setEnabled(true);
        jtiE.setEnabled(true);
        jcPessoa.setEnabled(true);
        jcPlat.setEnabled(true);
        jcEmpi.setEnabled(true);

        jrAtivo.setEnabled(true);
        jrInativo.setEnabled(true);

        jtCep.setEnabled(true);
        jbCep.setEnabled(true);
        jtCodIbge.setEnabled(true);
        jtCidade.setEnabled(true);
        jcUf.setEnabled(true);
        jtBairro.setEnabled(true);
        jtCompl.setEnabled(true);
        jtNum.setEnabled(true);
        jtRua.setEnabled(true);

        jtTelFixo.setEnabled(true);
        jtTelCel.setEnabled(true);
        jtMailCon.setEnabled(true);
        jtEndWeb.setEnabled(true);
        jtNomeCon.setEnabled(true);
        jtRntrc.setEnabled(true);
        jtTelCon.setEnabled(true);
        jtChapaV.setEnabled(true);

        jtHoraAtend.setEnabled(true);
        jtContato.setEnabled(true);

        jtCod.setEnabled(false);
        jbBuscarT.setEnabled(false);

        jbSalvar.setEnabled(true);
        jbNovo.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(true);

    }

    /**
     * Função do botao Cancelar
     */
    public void cancelar() {

        jbCnpj.setEnabled(false);

        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbNovo.setEnabled(true);

        jtCod.setEnabled(true);
        jbBuscarT.setEnabled(true);

        jtCnpj.setEnabled(false);
        jtRazaoS.setEnabled(false);
        jtApelido.setEnabled(false);
        jtiE.setEnabled(false);
        jcPessoa.setEnabled(false);
        jcPlat.setEnabled(false);
        jcEmpi.setEnabled(false);

        jrAtivo.setEnabled(false);
        jrInativo.setEnabled(false);

        jtCep.setEnabled(false);
        jbCep.setEnabled(false);
        jtCodIbge.setEnabled(false);
        jtCidade.setEnabled(false);
        jcUf.setEnabled(false);
        jtBairro.setEnabled(false);
        jtCompl.setEnabled(false);
        jtNum.setEnabled(false);
        jtRua.setEnabled(false);

        jtTelFixo.setEnabled(false);
        jtTelCel.setEnabled(false);
        jtMailCon.setEnabled(false);
        jtEndWeb.setEnabled(false);
        jtNomeCon.setEnabled(false);
        jtRntrc.setEnabled(false);
        jtTelCon.setEnabled(false);
        jtChapaV.setEnabled(false);

        jtHoraAtend.setEnabled(false);
        jtContato.setEnabled(false);

        jtCod.setText("");
        jtCnpj.setText("");
        jtRazaoS.setText("");
        jtApelido.setText("");
        jtiE.setText("");
        jcPessoa.setSelectedIndex(0);
        jcPlat.setSelectedIndex(0);
        jcEmpi.setSelectedIndex(0);

        jtCep.setText("");
        jtCodIbge.setText("");
        jtCidade.setText("");
        jcUf.setSelectedIndex(0);
        jtBairro.setText("");
        jtCompl.setText("");
        jtNum.setText("");
        jtRua.setText("");

        jtTelFixo.setText("");
        jtTelCel.setText("");
        jtMailCon.setText("");
        jtEndWeb.setText("");
        jtNomeCon.setText("");
        jtRntrc.setText("");
        jtTelCon.setText("");
        jtChapaV.setText("");
        jtQuem.setText(jtAcesso.getText());

    }

    /**
     * Preenche espaço no banco de dados para Salvar no Banco de Dados
     *
     */
    public void preencher_objetos() {

        objtra.setTra_cnpj(jtCnpj.getText());
        objtra.setTra_razaoS(jtRazaoS.getText());
        objtra.setTra_apelido(jtApelido.getText());
        objtra.setTra_iE(jtiE.getText());
        objtra.setTra_pessoa((String) jcPessoa.getSelectedItem());
        objtra.setTra_plat((String) jcPlat.getSelectedItem());
        objtra.setTra_empi((String) jcEmpi.getSelectedItem());

        objtra.setTra_status(status);

        objtra.setTra_cep(jtCep.getText());

        objtra.setTra_codIbge(jtCodIbge.getText());
        objtra.setTra_uf((String) jcUf.getSelectedItem());
        objtra.setTra_cidade(jtCidade.getText());
        objtra.setTra_rua(jtRua.getText());
        objtra.setTra_compl(jtCompl.getText());
        objtra.setTra_bairro(jtBairro.getText());
        objtra.setTra_num(jtNum.getText());

        objtra.setTra_telCel(jtTelCel.getText());
        objtra.setTra_telFixo(jtTelFixo.getText());
        objtra.setTra_mailCon(jtMailCon.getText());
        objtra.setTra_endWeb(jtEndWeb.getText());

        objtra.setTra_veiCon(jtNomeCon.getText());
        objtra.setTra_rntrc(jtRntrc.getText());
        objtra.setTra_veiTel(jtTelCon.getText());
        objtra.setTra_veiChapa(jtChapaV.getText());
        objtra.setTra_quemCad(jtQuem.getText());
        
        objtra.setTra_horAtend(jtHoraAtend.getText());
        objtra.setTra_contato(jtContato.getText());
    }

    /**
     * Pesquisa Transportadora com Base no COD Inserido
     */
    public void pesquisaTransportadora() {

        jtCnpj.setText(objtra.getTra_cnpj().trim());
        jtRazaoS.setText(objtra.getTra_razaoS().trim());
        jtApelido.setText(objtra.getTra_apelido().trim());
        jtiE.setText(objtra.getTra_iE().trim());
        jcPessoa.setSelectedItem(objtra.getTra_pessoa().trim());
        jcPlat.setSelectedItem(objtra.getTra_plat().trim());
        jcEmpi.setSelectedItem(objtra.getTra_empi().trim());

        jtCep.setText(objtra.getTra_cep());
        jtCodIbge.setText(objtra.getTra_codIbge());
        jcUf.setSelectedItem(objtra.getTra_uf());
        jtCidade.setText(objtra.getTra_cidade());
        jtRua.setText(objtra.getTra_rua());
        jtCompl.setText(objtra.getTra_compl());
        jtBairro.setText(objtra.getTra_bairro());
        jtNum.setText(objtra.getTra_num());

        jtTelCel.setText(objtra.getTra_telCel());
        jtTelFixo.setText(objtra.getTra_telFixo());
        jtMailCon.setText(objtra.getTra_mailCon());
        jtEndWeb.setText(objtra.getTra_endWeb());

        jtNomeCon.setText(objtra.getTra_veiCon());
        jtRntrc.setText(objtra.getTra_rntrc());
        jtTelCon.setText(objtra.getTra_veiTel());
        jtChapaV.setText(objtra.getTra_veiChapa());

        jtQuem.setText(objtra.getTra_quemCad());
        
        jtHoraAtend.setText(objtra.getTra_horAtend());
        jtContato.setText(objtra.getTra_contato());

        if (status == 1) {
            jrAtivo.setSelected(true);
        }
        if (status == 0) {
            jrInativo.setSelected(true);
        }

        jbEditar.setEnabled(true);
        jbExcluir.setEnabled(true);

    }

    /**
     * Pesquisa endreço com base no cep inserido
     *
     * @param cep
     */
    public void buscarCep(String cep) {
        try {
            URL url = new URL("http://viacep.com.br/ws/" + cep + "/xml");
            SAXReader xml = new SAXReader();
            Document documento = xml.read(url);
            Element root = documento.getRootElement();

            for (Iterator<Element> it = root.elementIterator(); it.hasNext();) {
                Element element = it.next();

                // if (jtRuaT3.getText().isEmpty()){
                if (element.getQualifiedName().equals("logradouro")) {
                    jtRua.setText(element.getText().toUpperCase());
                }

                //  } if(jtBairroT3.getText().isEmpty()){
                if (element.getQualifiedName().equals("bairro")) {
                    jtBairro.setText(element.getText().toUpperCase());
                }
                // }

                //  if (jtCidadeT3.getText().isEmpty()){
                if (element.getQualifiedName().equals("localidade")) {
                    jtCidade.setText(element.getText().toUpperCase());
                }
                // }

                if (element.getQualifiedName().equals("uf")) {
                    jcUf.setSelectedItem(element.getText());
                }
                if (element.getQualifiedName().equals("ibge")) {
                    jtCodIbge.setText(element.getText());
                }

            }
        } catch (Exception e) {

            System.err.println("Erro: " + e);
        }

    }

    public ConsultaCNPJController getController() {
        if (controller == null) {
            controller = new ConsultaCNPJController();
        }
        return controller;
    }

    /**
     * preenche dados do CNPJ com base na informação inserida
     */
    public void buscarCNPJ() {
        String cnpj = jtCnpj.getText();
        cnpj = cnpj.replaceAll("[^0123456789]", "");
        try {
            PessoaJuridica pessoa = getController().consulta(cnpj);

            if (pessoa != null) {

                jcUf.setSelectedItem(pessoa.getEstado().toUpperCase());
                jtRazaoS.setText(pessoa.getRazaoSocial().toUpperCase());
                jtBairro.setText(pessoa.getBairro().toUpperCase());
                jtRua.setText(pessoa.getRua().toUpperCase());
                jtNum.setText(pessoa.getNumero());
                jtTelFixo.setText(pessoa.getTelefone());
                jtCep.setText(pessoa.getCep());
                jtCompl.setText(pessoa.getComplemento().toUpperCase());
                jtMailCon.setText(pessoa.getEnderecoEletronico());
                jtCidade.setText(pessoa.getMunicipio().toUpperCase());

                if (pessoa.getSituacao().equals("ATIVA")) {
                    jrAtivo.setSelected(true);
                } else {
                    jrInativo.setSelected(true);
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "CNPJ n�o encontrado.");
        }
    }
}
